version: '3'
services:
    laravel:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
            - 443:443
            - LARAVEL_ENV=production
            - LARAVEL_DB_PASSWORD=
            - LARAVEL_DB_NAME=envault
            - LARAVEL_DB_HOST=mysql
            - LARAVEL_REDIS_HOST=redis
            - LARAVEL_REDIS_PASSWORD=
            - LARAVEL_URL_HOSTNAME=dominio.com.br
            - LARAVEL_URL_PROTOCOL=htpps
            - LARAVEL_URL_ENV=internet
            - CERTBOT_EMAIL=
            - NGINX_CONF=/etc/nginx/conf.d/envault.conf
        volumes:
            - '.:/usr/share/nginx/envault/'
            - './nginx/:/etc/nginx/conf.d/'
            - './letsencrypt/:/etc/letsencrypt/'
        networks:
            - laravel
        depends_on:
            - mysql
            - redis
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 10s
            timeout: 15s
            retries: 10
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "10"
    mysql:
        image: 'mariadb:10.7''
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: ''
            MARIADB_DATABASE: 'envault'
        volumes:
            - 'laravelmysql:/var/lib/mysql'
        networks:
            - laravel
    redis:
        image: 'redis:alpine'
        command: redis-server /etc/redis/redis.conf
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './redis/redis.conf:/etc/redis/redis.conf'
            - 'laravelredis:/data'
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    laravelmysql:
        driver: local
    laravelredis:
        driver: local
